### ISSUE TITLE
Add way to pass globals to standard

### ISSUE THREAD

**Issue by jhitchins88** [arschmitz/broccoli-standard#1]
Currently there are no ways to pass general options to the standard linter.  All options are specifically picked from the options object.  One option that would be useful to send to standard is `globals`.  Right now, you can "pass" it to standard by having it in your package.json, but this prevents addons from adding globals.

**Comment by arschmitz** [comment]
So i'm not against exposing this option however i'm not sure this would be the best solution to your use case. In this case it may be better to actually update to projects package.json from the addon's default blueprint  so its obvious where the global is coming from.
